name: Build and Push Docker Image on GCP Artifact Registry

on:
  push:
    branches: ['main']

env:
  REGISTRY_LOCATION: ${{ secrets.REGISTRY_LOCATION }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WIP }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
  BASE_IMAGE_TAG: ${{ secrets.REGISTRY_LOCATION }}/${{ secrets.PROJECT_ID }}/terraform-test

jobs:
  buildnpush:
    name: 'Build & Push'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_LOCATION }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build & Push Angular Image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BASE_IMAGE_TAG }}/angular:latest
          context: ./angular-terraform-dummy-app

      - name: Build & Push Java Image to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.BASE_IMAGE_TAG }}/java:latest
          context: ./terraform-java-project
  
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    steps:
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 30s

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Artifact Registry Cleaner
        uses: 'docker://europe-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.BASE_IMAGE_TAG }}/java
            -repo=${{ env.BASE_IMAGE_TAG }}/angular
            -grace=24h      