name: Terraform Apply

on:
  workflow_run:
    workflows: ["Build and Push Docker Image on GCP Artifact Registry"]
    types:
      - completed

env:
  REGISTRY_LOCATION: ${{ secrets.REGISTRY_LOCATION }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WIP }}
  PROJECT: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  ZONE: ${{ secrets.ZONE }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
  BASE_IMAGE_TAG: ${{ secrets.REGISTRY_LOCATION }}/${{ secrets.PROJECT_ID }}/terraform-test

jobs:
  apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: my-terraform-config
          auto_approve: true
          variables: |
            project = ${{ env.PROJECT }}
            access_token = ${{ steps.auth.outputs.access_token }}
            zone = ${{ env.ZONE }}
            region = ${{ env.REGION }}